name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore jhconvert.sln

    - name: Build
      run: dotnet build jhconvert.sln --configuration ${{ matrix.configuration }}

    - name: Publish
      run: dotnet publish jhconvert/jhconvert.csproj --configuration ${{ matrix.configuration }} --output ./publish /p:PublishSingleFile=true /p:RuntimeIdentifier=win-x64 /p:ReadyToRun=true /p:DebugType=none

    - name: Archive published files
      uses: actions/upload-artifact@v3
      with:
        name: published
        path: ./publish
